enum Format {
  DEFAULT,
  NORMAL,
  YEAR_MONTH_DAY_HOUR_MINUTE,
  YEAR_MONTH_DAY_HOUR,
  YEAR_MONTH_DAY,
  YEAR_MONTH,
  MONTH_DAY_HOUR_MINUTE_SECOND_MIN,
  MONTH_DAY_HOUR_MINUTE_SECOND,
  MONTH_DAY_HOUR_MINUTE,
  MONTH_DAY,
  HOUR_MINUTE_SECOND_MIN,
  HOUR_MINUTE_SECOND,
  HOUR_MINUTE
}